feat: add pre-commit hooks
BiomedSciAI/fuse-med-ml pull request #198
Opened 2022-10-25 16:37 UTC by ishita1805

**Issue** 
#197 

**Description** 
This PR adds the following format checkers as pre-commit hooks:
- eslint
- check-case-conflict
- pretty-format-json
- end-of-file-fixer
- mixed-line-ending
- trailing-whitespace
- double-quote-string-fixer

2022-10-29 15:43 UTC, SagiPolaczek requested changes
Thanks Ishita!

Note that the pre-commits hooks that we want to use are: `black`, `flake8` and `mypy`. Please consider visit [this](https://github.com/PyCQA/flake8/blob/main/.pre-commit-config.yaml) as a reference.
Also note that arguments should not be provided because we are using configuration files.

After applying those changes and the one in the in-line comment we shall merge.

Thanks and looking forward for your response @ishita1805 .

2022-10-29 15:43 UTC, SagiPolaczek commented on requirements_dev.txt
> +pre-commit
Please move to `fuse/requirements_dev.txt`

2022-10-29 15:43 UTC, SagiPolaczek commented on .pre-commit-config.yaml
> +      - id: double-quote-string-fixer
Note that this one contradicts `black` configuration, as it prefers double quotes upon single ones.

2022-10-30 18:40 UTC, ishita1805 commented
@SagiPolaczek I've updated the PR, please let me know if something else needs to be done

2022-10-30 21:25 UTC, SagiPolaczek approved these changes
Thanks Ishita! Looks good 😄

2022-10-31 17:20 UTC, SagiPolaczek commented
@ishita1805 

Just to inform you:
We currently have some env issue with the CI/CD. Your PR has already been approved and will be merge as soon as we'll solve the issue.

Thanks a lot for your contribution!

2022-11-02 10:38 UTC, mosheraboh approved these changes
Thanks a lot @ishita1805! Looks good.
 @SagiPolaczek I'm merging, but please note that the versions in pre_commit of black and mypy are not aligned with the versions in requirements_dev.txt.
 I will merge it anyway and if necessary align them in another PR.

2022-11-02 10:38 UTC, merged