Transformer + 1D/2D/3D Vision Transformer
BiomedSciAI/fuse-med-ml pull request #200
Opened 2022-10-31 10:51 UTC by avihu111

2022-10-31 14:29 UTC, mosheraboh requested changes
Thanks Avihu! Looks very good!
Please just add documentation to any not straightforward argument.
And move the main() to be a simple unittest

2022-10-31 14:29 UTC, mosheraboh commented on fuse/dl/models/backbones/backbone_vit.py
> +    def forward(self, x: torch.Tensor, pool: str = "none"):
doc got args

2022-10-31 14:30 UTC, mosheraboh commented
The jenkinks tests fail in all PRs. Sagi and I looking for a solution. You can ignore it for now.

2022-10-31 15:13 UTC, avihu111 commented on fuse/dl/models/backbones/backbone_vit.py
> +def main():
I changed it to be in the format of a code example.. think it's a nice code snippet.

2022-10-31 15:13 UTC, avihu111 commented on fuse/dl/models/backbones/backbone_vit.py
> +    def __init__(self, token_dim: int, projection_kwargs: dict, transformer_kwargs: dict):
think it is better now

2022-11-02 13:50 UTC, mosheraboh approved these changes

2022-11-02 13:51 UTC, merged

2022-11-03 10:30 UTC, egozi commented
I want to add a few things:
1. default parameters for depth, heads etc.
2. standard models like - vit_base, vit_large, …
3. the interpolation module for diff image sizes.
4. What about pre trained weights? and an option flag.

2022-11-03 10:39 UTC, SagiPolaczek commented
@egozi 
Hey Amir :) Sounds cool.

Could you please open an issue on those suggestions?
While its best to open with our templates, there is a quicker way to do so:  In the comment's menu click "Reference in a new issue".