loss wrapper to batch dict
BiomedSciAI/fuse-med-ml pull request #206
Opened 2022-11-06 12:20 UTC by avihu111

wraps a loss module to use the batch dict.

2022-11-07 01:24 UTC, akoseki2 approved these changes

2022-11-07 15:47 UTC, avihu111 commented
I added a usage example, hoping for faster code understanding.
@akoseki2 would you have another look please?

2022-11-08 08:57 UTC, mosheraboh requested changes
Thanks @avihu111, looks good!
See few minor requests inline

2022-11-08 08:57 UTC, mosheraboh commented on fuse/dl/losses/loss_wrap_to_dict.py
> +    Wraps a torch loss function to support a batch dict
Lets mention the usage_example

2022-11-10 06:53 UTC, akoseki2 approved these changes

2022-11-10 11:12 UTC, mosheraboh approved these changes

2022-11-10 11:44 UTC, merged